name             'osxdefaults'
maintainer       'Roderik van der Veer'
maintainer_email 'roderik@vanderveer.be'
license          'Apache 2.0'
description      'Installs/Configures osx defaults'
version          '1.0.4'
